services:
  postgres:
    image: postgres:13
    container_name: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=connectorbdb
    #volumes:
    #  - connector-data:/var/lib/postgresql/data
    networks:
      - local

  connector:
    image: ghcr.io/data-space-core/connector/stage:latest
    container_name: connector
    ports:
      - 8081:8081
    environment:
      - SERVER_PORT=8081
      
      - CONFIGURATION_PATH=/config/config.json
      - SERVER_SSL_KEY-STORE=file:///conf/testbed2.p12
      
      - DAPS_URL=https://omejdn
      - DAPS_TOKEN_URL=https://omejdn/auth/token
      - DAPS_KEY_URL=https://omejdn/auth/jwks.json
      - DAPS_INCOMING_DAT_DEFAULT_WELLKNOWN=/jwks.json
     
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/connectorbdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_DATASOURCE_PLATFORM=postgres
      - SPRING_DATASOURCE_DRIVERCLASSNAME=org.postgresql.Driver
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
    volumes:
      - ./conf/config.json:/config/config.json
      - ./conf/testbed2.p12:/conf/testbed2.p12
      - ./conf/truststore.p12:/config/truststore.p12
    networks:
      - local
    depends_on:
      - postgres

volumes:
  connector-datab: {}

networks:
  local:
    driver: bridge
